# Generated by Django 6.0.2 on 2026-03-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0006_livro_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="data_pub",
        ),
        migrations.AddField(
            model_name="livro",
            name="ano_pub",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
